# Generated by Django 2.1.7 on 2019-05-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='form_validate',
            field=models.BooleanField(default=False),
        ),
    ]
