# Generated by Django 2.1.7 on 2019-04-24 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Blood_type',
                'verbose_name_plural': 'Blood_types',
            },
        ),
        migrations.CreateModel(
            name='ClassEnrolled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Class Enrolled',
                'verbose_name_plural': 'Classes Enrolled',
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('time_ini', models.TimeField()),
                ('time_end', models.TimeField()),
                ('max_places', models.IntegerField()),
                ('rem_places', models.IntegerField()),
                ('ocu_places', models.IntegerField()),
            ],
            options={
                'verbose_name': 'class',
                'verbose_name_plural': 'classes',
                'ordering': ('date_id',),
            },
        ),
        migrations.CreateModel(
            name='Em_contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('relation', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Emergency_contact',
                'verbose_name_plural': 'Emergency_contacts',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Enrolled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birth_date', models.DateTimeField()),
                ('level', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('zip_code', models.IntegerField()),
                ('academy', models.CharField(max_length=100)),
                ('disease', models.CharField(max_length=200)),
                ('enrolled', models.BooleanField(default=False)),
                ('amount_en', models.IntegerField()),
                ('payed_courses', models.IntegerField()),
                ('total_payed', models.BooleanField(default=False)),
                ('blood_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_type', to='schedule.Blood_type')),
            ],
            options={
                'verbose_name': 'Enrolled',
                'verbose_name_plural': 'Enrolled',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('enrolled', models.IntegerField()),
                ('total_payed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=200)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=300)),
                ('cost1', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('cost2', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
            options={
                'ordering': ('level',),
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'program',
                'verbose_name_plural': 'programs',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('birth_date', models.DateTimeField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Weeks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('ini_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'week',
                'verbose_name_plural': 'weeks',
            },
        ),
        migrations.AddField(
            model_name='level',
            name='program_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level', to='schedule.Program'),
        ),
        migrations.AddField(
            model_name='enrolled',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_enrolled', to='schedule.Groups'),
        ),
        migrations.AddField(
            model_name='em_contact',
            name='enrolled',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Enrolled_contact', to='schedule.Enrolled'),
        ),
        migrations.AddField(
            model_name='classes',
            name='date_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schedule.Weeks'),
        ),
        migrations.AddField(
            model_name='classes',
            name='level_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schedule.Level'),
        ),
        migrations.AddField(
            model_name='classes',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schedule.Teacher'),
        ),
        migrations.AddField(
            model_name='classenrolled',
            name='id_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Class', to='schedule.Classes'),
        ),
        migrations.AddField(
            model_name='classenrolled',
            name='id_enrolled',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Student', to='schedule.Enrolled'),
        ),
        migrations.AddField(
            model_name='classenrolled',
            name='id_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Level', to='schedule.Level'),
        ),
        migrations.AddField(
            model_name='classenrolled',
            name='id_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Program', to='schedule.Program'),
        ),
        migrations.AlterIndexTogether(
            name='classenrolled',
            index_together={('id_class', 'id_enrolled')},
        ),
    ]
