# Generated by Django 2.1.7 on 2019-04-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='code',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
