# Generated by Django 2.1.7 on 2019-05-13 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TallerGuitarra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_class', models.CharField(choices=[('8-12 julio: 2 talleres', '8-12 julio: 2 talleres'), ('8-12 julio: 1 taller', '8-12 julio: 2 taller')], max_length=30)),
                ('id_enrolled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Guitar_Enrolled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Taller de Guitarra',
                'verbose_name_plural': 'Talleres de Guitarra',
            },
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
