# Generated by Django 2.1.7 on 2019-04-09 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20190408_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'ordering': ('date_id',), 'verbose_name': 'class', 'verbose_name_plural': 'classes'},
        ),
        migrations.AlterModelOptions(
            name='weeks',
            options={'verbose_name': 'week', 'verbose_name_plural': 'weeks'},
        ),
    ]
