# Generated by Django 2.1.7 on 2019-04-30 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20190427_1718'),
        ('schedule', '0002_auto_20190428_0946'),
    ]

    operations = [
    ]
