# Generated by Django 2.1.7 on 2019-04-24 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_remove_enrolled_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolled',
            name='mail',
        ),
    ]
