# Generated by Django 2.1.7 on 2019-05-13 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20190512_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tallerguitarra',
            name='id_class',
            field=models.CharField(choices=[('8-12 julio: 2 talleres', '8-12 julio: 2 talleres'), ('8-12 julio: 1 taller', '8-12 julio: 1 taller')], max_length=30),
        ),
    ]
