# Generated by Django 2.1.7 on 2019-05-08 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20190507_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolled',
            name='amount_en',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='enrolled',
            name='payed_courses',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='enrolled',
            name='total_payed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
