# Generated by Django 2.1.7 on 2019-06-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20190519_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='independiente',
            name='s3',
            field=models.CharField(blank=True, choices=[('NIVEL INTERMEDIO - Karen Lugo (Bambera)', 'NIVEL INTERMEDIO - Karen Lugo (Bambera)'), ('NIVEL AVANZADO - La Truco (Seguiriya)', 'NIVEL AVANZADO - La Truco (Seguiriya)'), ('NIVEL AVANZADO - Javier LaTorre (Alegrías)', 'NIVEL AVANZADO - Javier LaTorre (Alegrías)')], max_length=150),
        ),
        migrations.AlterField(
            model_name='independiente',
            name='s9',
            field=models.CharField(blank=True, choices=[('NIÑOS INTERMEDIO - Nazaret Reyes (Alegrías)', 'NIÑOS INTERMEDIO - Nazaret Reyes (Alegrías)'), ('NIVEL BÁSICO - José Galán', 'NIVEL BÁSICO - José Galán'), ('NIVEL BÁSICO - Pablo Egea', 'NIVEL BÁSICO - Pablo Egea'), ('NIVEL INTERMEDIO - El Carpeta (Seguiriyas)', 'NIVEL INTERMEDIO - El Carpeta (Seguiriyas)'), ('NIVEL INTERMEDIO - Eduardo Guerrero (Bulerías)', 'NIVEL INTERMEDIO - Eduardo Guerrero (Bulerías)'), ('NIVEL AVANZADO - María Moreno (Bata de Cola por Alegrías)', 'NIVEL AVANZADO - María Moreno (Bata de Cola por Alegrías)'), ('NIVEL AVANZADO - Ana Morales (Seguiriya)', 'NIVEL AVANZADO - Ana Morales (Seguiriya)'), ('NIVEL PROFESIONAL - Pedro Córdoba', 'NIVEL PROFESIONAL - Pedro Córdoba')], max_length=150),
        ),
    ]
