# Generated by Django 2.1.7 on 2019-05-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20190507_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolled',
            name='amount_en',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrolled',
            name='enrolled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='enrolled',
            name='payed_courses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrolled',
            name='total_payed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
