# Generated by Django 2.1.7 on 2019-05-13 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0003_auto_20190512_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_class', models.CharField(choices=[('8-12 julio (Semana 1)', '8-19 julio (Semana 1)'), ('15-19 julio (Semana 2)', '15-19 julio (Semana 2)'), ('8-19 julio (Dos semanas)', '8-19 julio (Dos semanas)'), ('1 día', '1 día')], max_length=30)),
                ('id_enrolled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Observer_Enrolled', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
