# Generated by Django 2.1.7 on 2019-06-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20190603_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intensivo',
            name='i1m1',
            field=models.CharField(blank=True, choices=[('El Carpeta (Bulerías)', 'El Carpeta (Bulerías)'), ('Nazaret Reyes (Alegrías)', 'Nazaret Reyes (Alegrías)'), ('NIVEL AVANZADO - Rafael Estévez (Cantiña del amarano)', 'NIVEL AVANZADO - Rafael Estévez (Cantiña del amarano)'), ('NIVEL AVANZADO - Valeriano Paños (Martinete)', 'NIVEL AVANZADO - Valeriano Paños (Martinete)')], max_length=150),
        ),
        migrations.AlterField(
            model_name='intensivo',
            name='i1m2',
            field=models.CharField(blank=True, choices=[('Rafael Estévez (Tangos)', 'Rafael Estévez (Tangos)'), ('Nazaret Reyes (Caña)', 'Nazaret Reyes (Caña)'), ('NIVEL AVANZADO - La Truco (Soleá)', 'NIVEL AVANZADO - La Truco (Soleá)'), ('NIVEL AVANZADO - Javier LaTorre (Taranto)', 'NIVEL AVANZADO - Javier LaTorre (Taranto)')], max_length=150),
        ),
        migrations.AlterField(
            model_name='intensivo',
            name='i1v1',
            field=models.CharField(blank=True, choices=[('María Juncal (Fandangos)', 'María Juncal (Fandangos)'), ('NIVEL AVANZADO - Pedro Córdoba (Soleá por bulería)', 'NIVEL AVANZADO - Pedro Córdoba (Soleá por bulería)'), ('NIVEL AVANZADO - Ana Morales (Soleá)', 'NIVEL AVANZADO - Ana Morales (Soleá)')], max_length=150),
        ),
        migrations.AlterField(
            model_name='intensivo',
            name='i1v2',
            field=models.CharField(blank=True, choices=[('Ana Morales (Alegrías de Córdoba)', 'Ana Morales (Alegrías de Córdoba)'), ('NIVEL AVANZADO - María Juncal (Guajira)', 'NIVEL AVANZADO - María Juncal (Guajira)'), ('NIVEL AVANZADO - Pedro Córdoba (Martinete)', 'NIVEL AVANZADO - Pedro Córdoba (Martinete)')], max_length=150),
        ),
        migrations.AlterField(
            model_name='intensivo',
            name='i2m1',
            field=models.CharField(blank=True, choices=[('Eduardo Guerrero (Bulerías)', 'Eduardo Guerrero (Bulerías)'), ('El Carpeta (Seguiriyas)', 'El Carpeta (Seguiriyas)'), ('NIVEL AVANZADO - María Moreno (Bata de Cola por Alegrías)', 'NIVEL AVANZADO - María Moreno (Bata de Cola por Alegrías)'), ('NIVEL AVANZADO - Ana Morales (Seguiriya)', 'NIVEL AVANZADO - Ana Morales (Seguiriya)')], max_length=150),
        ),
        migrations.AlterField(
            model_name='intensivo',
            name='i2m2',
            field=models.CharField(blank=True, choices=[('María Moreno (Romance)', 'María Moreno (Romance)'), ('Ana Morales (Guajira)', 'Ana Morales (Guajira)'), ('NIVEL AVANZADO - Pedro Córdoba (Soleá por bulería)', 'NIVEL AVANZADO - Pedro Córdoba (Soleá por bulería)'), ('NIVEL AVANZADO - Eduardo Guerrero (Fandango)', 'NIVEL AVANZADO - Eduardo Guerrero (Fandango)')], max_length=150),
        ),
        migrations.AlterField(
            model_name='intensivo',
            name='i2v1',
            field=models.CharField(blank=True, choices=[('Karen Lugo (Bambera)', 'Karen Lugo (Bambera)'), ('NIVEL AVANZADO - La Truco (Seguiriya)', 'NIVEL AVANZADO - La Truco (Seguiriya)'), ('NIVEL AVANZADO - Javier LaTorre (Alegrías)', 'NIVEL AVANZADO - Javier LaTorre (Alegrías)')], max_length=150),
        ),
        migrations.AlterField(
            model_name='intensivo',
            name='i2v2',
            field=models.CharField(blank=True, choices=[('Juan Paredes (Bailes festeros por bulerías)', 'Juan Paredes (Bailes festeros por bulerías)'), ('NIVEL AVANZADO - Javier LaTorre (Farruca)', 'NIVEL AVANZADO - Javier LaTorre (Farruca)'), ('NIVEL AVANZADO - Karen Lugo (Martinete)', 'NIVEL AVANZADO - Karen Lugo (Martinete)')], max_length=150),
        ),
    ]
