# Generated by Django 2.2.1 on 2019-05-14 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_observador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observador',
            options={'verbose_name': 'Observador', 'verbose_name_plural': 'Observadores'},
        ),
    ]
