# Generated by Django 2.1.7 on 2019-06-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20190604_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemental',
            name='j1',
            field=models.CharField(blank=True, choices=[('9:00 am 10:30 am | Pablo Egea', '9:00 am 10:30 am | Pablo Egea'), ('9:00 am 10:30 am | Juan Paredes (Bailes festeros por tangos)', '9:00 am 10:30 am | Juan Paredes (Bailes festeros por tangos)'), ('10:35 am - 12:05 pm | Valeriano Paños (Farruca)', '10:35 am - 12:05 pm | Valeriano Paños (Farruca)')], max_length=150),
        ),
    ]
