# Generated by Django 2.1.7 on 2019-05-08 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20190507_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolled',
            name='amount_en',
        ),
        migrations.RemoveField(
            model_name='enrolled',
            name='enrolled',
        ),
        migrations.RemoveField(
            model_name='enrolled',
            name='group',
        ),
        migrations.RemoveField(
            model_name='enrolled',
            name='payed_courses',
        ),
        migrations.RemoveField(
            model_name='enrolled',
            name='total_payed',
        ),
    ]
