# Generated by Django 2.1.7 on 2019-05-15 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0004_observador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week1_12', models.CharField(choices=[('Cristóbal Reyes "Valoración del Flamenco"', 'Cristóbal Reyes "Valoración del Flamenco"'), ('Eduardo Alves "Técnica de Danza Clásica" Nivel Intermedio', 'Eduardo Alves "Técnica de Danza Clásica" Nivel Intermedio'), ('Nuria Balbaneda "Técnica de Danza Clásica" Nivel Avanzado', 'Nuria Balbaneda "Técnica de Danza Clásica" Nivel Avanzado'), ('La Truco "Certificaciones de la EFA para Nivel Básico" Solo Avanzados (NUEVO)', 'La Truco "Certificaciones de la EFA para Nivel Básico" Solo Avanzados (NUEVO)'), ('Juan Paredes "Siente el Flamenco"', 'Juan Paredes "Siente el Flamenco"'), ('Carlos López Aragón "Danza Flamenca Urbana"', 'Carlos López Aragón "Danza Flamenca Urbana"'), ('Maribel Gallardo "Técnica de Danza Española" Castañuelas, Vueltas y Braceos', 'Maribel Gallardo "Técnica de Danza Española" Castañuelas, Vueltas y Braceos'), ('José Galán "Flamenco Inclusivo" Dirigido a Niveles Intermedio y Avanzado (NUEVO)', 'José Galán "Flamenco Inclusivo" Dirigido a Niveles Intermedio y Avanzado (NUEVO)')], max_length=150)),
                ('week1_13', models.CharField(choices=[('Cristóbal Reyes "Valoración del Flamenco"', 'Cristóbal Reyes "Valoración del Flamenco"'), ('Eduardo Alves "Técnica de Danza Clásica" Nivel Básico', 'Eduardo Alves "Técnica de Danza Clásica" Nivel Básico'), ('Nuria Balbaneda "Coreografía de Danza Clásica" Nivel Intermedio y Avanzado', 'Nuria Balbaneda "Coreografía de Danza Clásica" Nivel Intermedio y Avanzado'), ('Ana López "Estilización y Escuela Bolera"', 'Ana López "Estilización y Escuela Bolera"'), ('María Juncal "Técnica de Brazos y Cuerpo"', 'María Juncal "Técnica de Brazos y Cuerpo"'), ('Carlos López Aragón "Acrodanza"', 'Carlos López Aragón "Acrodanza"'), ('Maribel Gallardo "Repertorio de la Danza Española" Goyescas (Abanico) y La Vida Breve (Castañuelas)', 'Maribel Gallardo "Repertorio de la Danza Española" Goyescas (Abanico) y La Vida Breve (Castañuelas)')], max_length=150)),
                ('week2_12', models.CharField(choices=[('Eduardo Alves "Técnica de Danza Clásica" Nivel Intermedio', 'Eduardo Alves "Técnica de Danza Clásica" Nivel Intermedio'), ('Nuria Balbaneda "Técnica de Danza Clásica" Nivel Avanzado', 'Nuria Balbaneda "Técnica de Danza Clásica" Nivel Avanzado'), ('Cristóbal Reyes "Valoración del Flamenco"', 'Cristóbal Reyes "Valoración del Flamenco"'), ('María Juncal "Técnica de Pies"', 'María Juncal "Técnica de Pies"'), ('José Galán "Flamenco Inclusivo" Dirigido a Niveles Intermedio y Avanzado     (NUEVO)', 'José Galán "Flamenco Inclusivo" Dirigido a Niveles Intermedio y Avanzado     (NUEVO)'), ('Maribel Gallardo "Técnica de Danza Española" Castañuelas, Vueltas y Braceos', 'Maribel Gallardo "Técnica de Danza Española" Castañuelas, Vueltas y Braceos'), ('Raquel Ruiz "Neo Folk"', 'Raquel Ruiz "Neo Folk"'), ('Ana López "Estilización y Escuela Bolera"', 'Ana López "Estilización y Escuela Bolera"')], max_length=150)),
                ('week2_13', models.CharField(choices=[('Cristóbal Reyes "Valoración del Flamenco"', 'Cristóbal Reyes "Valoración del Flamenco"'), ('Eduardo Alves "Técnica de Danza Clásica" Nivel Básico', 'Eduardo Alves "Técnica de Danza Clásica" Nivel Básico'), ('Nuria Balbaneda "Coreografía de Danza Clásica" Nivel Intermedio y Avanzado', 'Nuria Balbaneda "Coreografía de Danza Clásica" Nivel Intermedio y Avanzado'), ('Juan Paredes "Siente el Flamenco"', 'Juan Paredes "Siente el Flamenco"'), ('La Truco "Certificaciones de la EFA para Nivel Intermedio" Solo Avanzados (NUEVO)', 'La Truco "Certificaciones de la EFA para Nivel Intermedio" Solo Avanzados (NUEVO)'), ('Maribel Gallardo "Repertorio de la Danza Española" Goyescas (Abanico) y La Vida Breve (Castañuelas)', 'Maribel Gallardo "Repertorio de la Danza Española" Goyescas (Abanico) y La Vida Breve (Castañuelas)'), ('Raquel Ruiz "Neo Folk"', 'Raquel Ruiz "Neo Folk"')], max_length=150)),
                ('id_enrolled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Inter_Enrolled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interdisciplinario',
                'verbose_name_plural': 'Interdisciplinarios',
            },
        ),
        migrations.AlterModelOptions(
            name='observador',
            options={'verbose_name': 'Observador', 'verbose_name_plural': 'Observadores'},
        ),
    ]
