# Generated by Django 2.1.7 on 2019-05-15 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20190514_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='inter',
            name='weeks',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
