# Generated by Django 2.1.7 on 2019-04-30 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20190430_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolled',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_enrolled', to='schedule.Groups'),
        ),
    ]
