# Generated by Django 2.1.7 on 2019-05-08 03:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0007_auto_20190507_2244'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrolled',
            unique_together={('user',)},
        ),
    ]
