# Generated by Django 2.1.7 on 2019-05-16 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0007_auto_20190514_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intensivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n1m1', models.CharField(blank=True, choices=[('José Galán', 'José Galán')], max_length=150)),
                ('n1m2', models.CharField(blank=True, choices=[('Manuel Fernández "El carpeta" (Seguiriyas)', 'Manuel Fernández "El carpeta" (Seguiriyas)')], max_length=150)),
                ('n2m1', models.CharField(blank=True, choices=[('Nazaret Reyes (Alegrías)', 'Nazaret Reyes (Alegrías)')], max_length=150)),
                ('n2m2', models.CharField(blank=True, choices=[('María Juncal (Tientos)', 'María Juncal (Tientos)')], max_length=150)),
                ('b1m1', models.CharField(blank=True, choices=[('Juan Paredes (Bailes festeros por tangos)', 'Juan Paredes (Bailes festeros por tangos)')], max_length=150)),
                ('b1m2', models.CharField(blank=True, choices=[('Valeriano Paños (Farruca)', 'Valeriano Paños (Farruca)')], max_length=150)),
                ('b2m1', models.CharField(blank=True, choices=[('Pablo Egea', 'Pablo Egea')], max_length=150)),
                ('b2m2', models.CharField(blank=True, choices=[('Nazaret Reyes (Tangos)', 'Nazaret Reyes (Tangos)')], max_length=150)),
                ('i1m1', models.CharField(blank=True, choices=[('El Carpeta (Bulerías)', 'El Carpeta (Bulerías)'), ('Nazaret Reyes (Alegrías)', 'Nazaret Reyes (Alegrías)')], max_length=150)),
                ('i1m2', models.CharField(blank=True, choices=[('Rafael Estévez (Tangos)', 'Rafael Estévez (Tangos)'), ('Nazaret Reyes (Caña)', 'Nazaret Reyes (Caña)')], max_length=150)),
                ('i1v1', models.CharField(blank=True, choices=[('María Juncal (Fandangos)', 'María Juncal (Fandangos)')], max_length=150)),
                ('i1v2', models.CharField(blank=True, choices=[('Ana Morales (Alegrías de Córdoba)', 'Ana Morales (Alegrías de Córdoba)')], max_length=150)),
                ('i2m1', models.CharField(blank=True, choices=[('Eduardo Guerrero (Bulerías)', 'Eduardo Guerrero (Bulerías)'), ('El Carpeta (Seguiriyas)', 'El Carpeta (Seguiriyas)')], max_length=150)),
                ('i2m2', models.CharField(blank=True, choices=[('María Moreno (Romance)', 'María Moreno (Romance)'), ('Ana Morales (Guajira)', 'Ana Morales (Guajira)')], max_length=150)),
                ('i2v1', models.CharField(blank=True, choices=[('Karen Lugo (Bambera)', 'Karen Lugo (Bambera)')], max_length=150)),
                ('i2v2', models.CharField(blank=True, choices=[('Juan Paredes (Bailes festeros por bulerías)', 'Juan Paredes (Bailes festeros por bulerías)')], max_length=150)),
                ('a1m1', models.CharField(blank=True, choices=[('Valeriano Paños (Martinete)', 'Valeriano Paños (Martinete)'), ('Rafael Estevez (Cantiña del amarano)', 'Rafael Estevez (Cantiña del amarano)'), ('Javier LaTorre (Guajira) -Grupo exclusivo para maestros y/o bailarines profesionales-', 'Javier LaTorre (Guajira) -Grupo exclusivo para maestros y/o bailarines profesionales-')], max_length=150)),
                ('a1m2', models.CharField(blank=True, choices=[('Javier LaTorre (Taranto)', 'Javier LaTorre (Taranto)'), ('La Truco (Soleá)', 'La Truco (Soleá)')], max_length=150)),
                ('a1v1', models.CharField(blank=True, choices=[('Ana Morales (Soleá)', 'Ana Morales (Soleá)'), ('Pedro Córdoba (Soleá por bulería)', 'Pedro Córdoba (Soleá por bulería)')], max_length=150)),
                ('a1v2', models.CharField(blank=True, choices=[('Pedro Córdoba (Soleá por bulería)', 'Pedro Córdoba (Soleá por bulería)'), ('María Juncal (Guajira)', 'María Juncal (Guajira)')], max_length=150)),
                ('a2m1', models.CharField(blank=True, choices=[('Ana Morales (Seguiriya)', 'Ana Morales (Seguiriya)'), ('María Moreno (Soleá por bulería)', 'María Moreno (Soleá por bulería)'), ('Pedro Córdoba (Jaleos) -Grupo exclusivo para maestros y/o bailarines profesionales-', 'Pedro Córdoba (Jaleos) -Grupo exclusivo para maestros y/o bailarines profesionales-')], max_length=150)),
                ('a2m2', models.CharField(blank=True, choices=[('Eduardo Guerrero (Fandango)', 'Eduardo Guerrero (Fandango)'), ('Pedro Córdoba (Soleá por Bulería)', 'Pedro Córdoba (Soleá por Bulería)')], max_length=150)),
                ('a2v1', models.CharField(blank=True, choices=[('Javier LaTorre (Alegrías)', 'Javier LaTorre (Alegrías)'), ('La Truco (Seguiriya)', 'La Truco (Seguiriya)')], max_length=150)),
                ('a2v2', models.CharField(blank=True, choices=[('Karen Lugo (Martinete)', 'Karen Lugo (Martinete)'), ('Javier LaTorre (Farruca)', 'Javier LaTorre (Farruca)')], max_length=150)),
                ('level', models.CharField(blank=True, max_length=20)),
                ('weeks', models.CharField(blank=True, max_length=50)),
                ('id_enrolled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Intensivo_Enrolled', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
