# Generated by Django 2.1.7 on 2019-05-17 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_intensivo_turn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intensivo',
            options={'verbose_name': 'Intensivo', 'verbose_name_plural': 'Intensivos'},
        ),
    ]
