# Generated by Django 2.1.7 on 2019-05-17 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0010_auto_20190516_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elemental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, max_length=20)),
                ('weeks', models.CharField(blank=True, max_length=50)),
                ('n1', models.CharField(blank=True, choices=[('Pablo Egea', 'Pablo Egea')], max_length=150)),
                ('n2', models.CharField(blank=True, choices=[('El Carpeta (Alegría)', 'El Carpeta (Alegría)')], max_length=150)),
                ('j1', models.CharField(blank=True, choices=[('9:00 am 10:30 am | Juan Paredes (Bailes festeros por tangos)', '9:00 am 10:30 am | Juan Paredes (Bailes festeros por tangos)'), ('10:35 am - 12:05 pm | Valeriano Paños (Farruca)', '10:35 am - 12:05 pm | Valeriano Paños (Farruca)')], max_length=150)),
                ('j2', models.CharField(blank=True, choices=[('9:00 am - 10:30 am | José Galán', '9:00 am - 10:30 am | José Galán'), ('10:35 am - 12:05 pm | Nazaret Reyes (Tangos)', '10:35 am - 12:05 pm | Nazaret Reyes (Tangos)')], max_length=150)),
                ('id_enrolled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Elemental_Enrolled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Elemental',
                'verbose_name_plural': 'Elementales',
            },
        ),
    ]
