# Generated by Django 2.1.7 on 2019-05-17 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0011_elemental'),
    ]

    operations = [
        migrations.CreateModel(
            name='Independiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weeks', models.CharField(blank=True, max_length=50)),
                ('p9', models.CharField(blank=True, choices=[('NIÑOS INTERMEDIO - José Galán', 'NIÑOS INTERMEDIO - José Galán'), ('NIVEL BÁSICO - Juan Paredes (Bailes festeros por tangos)', 'NIVEL BÁSICO - Juan Paredes (Bailes festeros por tangos)'), ('NIVEL INTERMEDIO - Nazaret Reyes (Alegrías)', 'NIVEL INTERMEDIO - Nazaret Reyes (Alegrías)'), ('NIVEL INTERMEDIO - El Carpeta (Bulerías)', 'NIVEL INTERMEDIO - El Carpeta (Bulerías)'), ('NIVEL AVANZADO - Rafael Estévez (Cantiña del amarano)', 'NIVEL AVANZADO - Rafael Estévez (Cantiña del amarano)'), ('NIVEL AVANZADO - Valeriano Paños (Martinete)', 'NIVEL AVANZADO - Valeriano Paños (Martinete)'), ('NIVEL PROFESIONAL - Javier LaTorre', 'NIVEL PROFESIONAL - Javier LaTorre')], max_length=150)),
                ('p10', models.CharField(blank=True, choices=[('NIÑOS BÁSICO - Pablo Egea', 'NIÑOS BÁSICO - Pablo Egea'), ('NIÑOS INTERMEDIO - El Carpeta (Seguiriyas)', 'NIÑOS INTERMEDIO - El Carpeta (Seguiriyas)'), ('NIVEL BÁSICO - Valeriano Paños (Farruca)', 'NIVEL BÁSICO - Valeriano Paños (Farruca)'), ('NIVEL INTERMEDIO - Rafael Estévez (Tangos)', 'NIVEL INTERMEDIO - Rafael Estévez (Tangos)'), ('NIVEL INTERMEDIO - Nazaret Reyes (Caña)', 'NIVEL INTERMEDIO - Nazaret Reyes (Caña)'), ('NIVEL AVANZADO - La Truco (Soleá)', 'NIVEL AVANZADO - La Truco (Soleá)'), ('NIVEL AVANZADO - Javier LaTorre (Taranto)', 'NIVEL AVANZADO - Javier LaTorre (Taranto)')], max_length=150)),
                ('p3', models.CharField(blank=True, choices=[('NIVEL INTERMEDIO - María Juncal (Fandangos)', 'NIVEL INTERMEDIO - María Juncal (Fandangos)'), ('NIVEL AVANZADO - Pedro Córdoba (Soleá por bulería)', 'NIVEL AVANZADO - Pedro Córdoba (Soleá por bulería)'), ('NIVEL AVANZADO - Ana Morales (Soleá)', 'NIVEL AVANZADO - Ana Morales (Soleá)')], max_length=150)),
                ('p5', models.CharField(blank=True, choices=[('NIVEL INTERMEDIO - Ana Morales (Alegrías de Córdoba)', 'NIVEL INTERMEDIO - Ana Morales (Alegrías de Córdoba)'), ('NIVEL AVANZADO - María Juncal (Guajira)', 'NIVEL AVANZADO - María Juncal (Guajira)'), ('NIVEL AVANZADO - Pedro Córdoba (Martinete)', 'NIVEL AVANZADO - Pedro Córdoba (Martinete)')], max_length=150)),
                ('s9', models.CharField(blank=True, choices=[('NIÑOS INTERMEDIO - Nazaret Reyes (Alegrías)', 'NIÑOS INTERMEDIO - Nazaret Reyes (Alegrías)'), ('NIVEL BÁSICO - José Galán', 'NIVEL BÁSICO - José Galán'), ('NIVEL INTERMEDIO - El Carpeta (Seguiriyas)', 'NIVEL INTERMEDIO - El Carpeta (Seguiriyas)'), ('NIVEL INTERMEDIO - Eduardo Guerrero (Bulerías)', 'NIVEL INTERMEDIO - Eduardo Guerrero (Bulerías)'), ('NIVEL AVANZADO - María Moreno (Bata de Cola por Alegrías)', 'NIVEL AVANZADO - María Moreno (Bata de Cola por Alegrías)'), ('NIVEL AVANZADO - Ana Morales (Seguiriya)', 'NIVEL AVANZADO - Ana Morales (Seguiriya)'), ('NIVEL PROFESIONAL - Pedro Córdoba', 'NIVEL PROFESIONAL - Pedro Córdoba')], max_length=150)),
                ('s10', models.CharField(blank=True, choices=[('NIÑOS BÁSICO - El Carpeta (Alegría)', 'NIÑOS BÁSICO - El Carpeta (Alegría)'), ('NIÑOS INTERMEDIO - María Juncal (Tientos)', 'NIÑOS INTERMEDIO - María Juncal (Tientos)'), ('NIVEL BÁSICO - Nazaret Reyes (Tangos)', 'NIVEL BÁSICO - Nazaret Reyes (Tangos)'), ('NIVEL INTERMEDIO - Ana Morales (Guajira)', 'NIVEL INTERMEDIO - Ana Morales (Guajira)'), ('NIVEL INTERMEDIO - María Moreno (Romance)', 'NIVEL INTERMEDIO - María Moreno (Romance)'), ('NIVEL AVANZADO - Pedro Córdoba (Soleá por bulería)', 'NIVEL AVANZADO - Pedro Córdoba (Soleá por bulería)'), ('NIVEL AVANZADO - Eduardo Guerrero (Fandango)', 'NIVEL AVANZADO - Eduardo Guerrero (Fandango)')], max_length=150)),
                ('s3', models.CharField(blank=True, choices=[('NIVEL INTERMEDIO - Juan Paredes (Bailes festeros, bulerías)', 'NIVEL INTERMEDIO - Juan Paredes (Bailes festeros, bulerías)'), ('NIVEL AVANZADO - Javier LaTorre (Farruca)', 'NIVEL AVANZADO - Javier LaTorre (Farruca)'), ('NIVEL AVANZADO - Karen Lugo (Martinete)', 'NIVEL AVANZADO - Karen Lugo (Martinete)')], max_length=150)),
                ('s5', models.CharField(blank=True, choices=[('NIVEL INTERMEDIO - Juan Paredes (Bailes festeros, bulerías)', 'NIVEL INTERMEDIO - Juan Paredes (Bailes festeros, bulerías)'), ('NIVEL AVANZADO - Javier LaTorre (Farruca)', 'NIVEL AVANZADO - Javier LaTorre (Farruca)'), ('NIVEL AVANZADO - Karen Lugo (Martinete)', 'NIVEL AVANZADO - Karen Lugo (Martinete)')], max_length=150)),
                ('id_enrolled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Independiente_Enrolled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Independiente',
                'verbose_name_plural': 'Independientes',
            },
        ),
    ]
