# Generated by Django 2.1.7 on 2019-05-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_independiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='independiente',
            name='classes',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='inter',
            name='week2_12',
            field=models.CharField(blank=True, choices=[('Eduardo Alves "Técnica de Danza Clásica" Nivel Intermedio', 'Eduardo Alves "Técnica de Danza Clásica" Nivel Intermedio'), ('Nuria Balbaneda "Técnica de Danza Clásica" Nivel Avanzado', 'Nuria Balbaneda "Técnica de Danza Clásica" Nivel Avanzado'), ('Cristóbal Reyes "Valoración del Flamenco"', 'Cristóbal Reyes "Valoración del Flamenco"'), ('María Juncal "Técnica de Pies"', 'María Juncal "Técnica de Pies"'), ('José Galán "Flamenco Inclusivo" Dirigido a Niveles Intermedio y Avanzado (NUEVO)', 'José Galán "Flamenco Inclusivo" Dirigido a Niveles Intermedio y Avanzado (NUEVO)'), ('Maribel Gallardo "Técnica de Danza Española" Castañuelas, Vueltas y Braceos', 'Maribel Gallardo "Técnica de Danza Española" Castañuelas, Vueltas y Braceos'), ('Raquel Ruiz "Neo Folk"', 'Raquel Ruiz "Neo Folk"'), ('Ana López "Estilización y Escuela Bolera"', 'Ana López "Estilización y Escuela Bolera"')], max_length=150),
        ),
    ]
