# Generated by Django 2.1.7 on 2019-05-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_auto_20190517_1607'),
        ('schedule', '0005_auto_20190514_0923'),
    ]

    operations = [
    ]
