# Generated by Django 2.1.7 on 2019-05-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_merge_20190518_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tallerguitarra',
            name='id_class',
        ),
        migrations.AddField(
            model_name='tallerguitarra',
            name='classes',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='tallerguitarra',
            name='s1',
            field=models.CharField(blank=True, choices=[('8-12 julio, 9:00 am - 12:00 pm: Román Vicenti', '8-12 julio, 9:00 am - 12:00 pm: Román Vicenti')], max_length=30),
        ),
        migrations.AddField(
            model_name='tallerguitarra',
            name='s2',
            field=models.CharField(blank=True, choices=[('15-17 julio, 9:00 am - 12:00 pm: Oscar Lagos', '15-17 julio, 9:00 am - 12:00 pm: Oscar Lagos')], max_length=30),
        ),
        migrations.AddField(
            model_name='tallerguitarra',
            name='s3',
            field=models.CharField(blank=True, choices=[('18-20 julio, 9:00 am - 12:00 pm: Antonio Campos y Jose Luis Medina', '18-20 julio, 9:00 am - 12:00 pm: Antonio Campos y Jose Luis Medina')], max_length=30),
        ),
    ]
